/** Confirmed haydockcommentary.com slugs. Omit a book rather than risk a 404. */
export const HAYDOCK_SLUG: Record<string, { slug: string; max: number }> = {
  Genesis: { slug: "genesis", max: 50 },
  Exodus: { slug: "exodus", max: 40 },
  Leviticus: { slug: "leviticus", max: 27 },
  Numbers: { slug: "numbers", max: 36 },
  Deuteronomy: { slug: "deuteronomy", max: 34 },
  Joshua: { slug: "joshua", max: 24 },
  Judges: { slug: "judges", max: 21 },
  Ruth: { slug: "ruth", max: 4 },
  "1 Samuel": { slug: "1-kings", max: 31 },
  "2 Samuel": { slug: "2-kings", max: 24 },
  "1 Kings": { slug: "3-kings", max: 22 },
  "2 Kings": { slug: "4-kings", max: 25 },
  "1 Chronicles": { slug: "1-paralipomenon", max: 29 },
  "2 Chronicles": { slug: "2-paralipomenon", max: 36 },
  Ezra: { slug: "1-esdras", max: 10 },
  Nehemiah: { slug: "2-esdras", max: 13 },
  Tobit: { slug: "tobias", max: 14 },
  Judith: { slug: "judith", max: 16 },
  Esther: { slug: "esther", max: 10 },
  "1 Maccabees": { slug: "1-machabees", max: 16 },
  "2 Maccabees": { slug: "2-machabees", max: 15 },
  Job: { slug: "job", max: 42 },
  Psalms: { slug: "psalm", max: 150 },
  Proverbs: { slug: "proverbs", max: 31 },
  Ecclesiastes: { slug: "ecclesiastes", max: 11 },
  Wisdom: { slug: "wisdom", max: 19 },
  Sirach: { slug: "ecclesiasticus", max: 51 },
  Isaiah: { slug: "isaias", max: 66 },
  Jeremiah: { slug: "jeremias", max: 3 },
  Lamentations: { slug: "lamentations", max: 5 },
  Baruch: { slug: "baruch", max: 6 },
  Ezekiel: { slug: "ezechiel", max: 48 },
  Daniel: { slug: "daniel", max: 14 },
  Hosea: { slug: "osee", max: 14 },
  Joel: { slug: "joel", max: 3 },
  Amos: { slug: "amos", max: 9 },
  Obadiah: { slug: "abdias", max: 1 },
  Jonah: { slug: "jonas", max: 4 },
  Micah: { slug: "micheas", max: 7 },
  Nahum: { slug: "nahum", max: 3 },
  Habakkuk: { slug: "habacuc", max: 3 },
  Zephaniah: { slug: "sophonias", max: 3 },
  Haggai: { slug: "aggeus", max: 2 },
  Zechariah: { slug: "zacharias", max: 14 },
  Malachi: { slug: "malachias", max: 3 },
  Matthew: { slug: "matthew", max: 28 },
  Mark: { slug: "mark", max: 16 },
  Luke: { slug: "luke", max: 24 },
  John: { slug: "john", max: 21 },
  "Acts of the Apostles": { slug: "acts-of-apostles", max: 28 },
  Romans: { slug: "romans", max: 16 },
  "1 Corinthians": { slug: "1-corinthians", max: 16 },
  "2 Corinthians": { slug: "2-corinthians", max: 13 },
  Galatians: { slug: "galatians", max: 6 },
  Ephesians: { slug: "ephesians", max: 6 },
  Philippians: { slug: "philippians", max: 4 },
  Colossians: { slug: "colossians", max: 4 },
  "1 Thessalonians": { slug: "1-thessalonians", max: 5 },
  "2 Thessalonians": { slug: "2-thessalonians", max: 3 },
  "1 Timothy": { slug: "1-timothy", max: 6 },
  "2 Timothy": { slug: "2-timothy", max: 4 },
  Titus: { slug: "titus", max: 3 },
  Philemon: { slug: "philemon", max: 1 },
  Hebrews: { slug: "hebrews", max: 13 },
  James: { slug: "james", max: 5 },
  "1 Peter": { slug: "1-peter", max: 5 },
  "2 Peter": { slug: "2-peter", max: 3 },
  "1 John": { slug: "1-john", max: 5 },
  "2 John": { slug: "2-john", max: 1 },
  "3 John": { slug: "3-john", max: 1 },
  Jude: { slug: "jude", max: 1 },
  Revelation: { slug: "apocalypse", max: 22 },
};

export function haydockUrl(book: string, chapter: number): string | null {
  const spec = HAYDOCK_SLUG[book];
  if (!spec || chapter < 1 || chapter > spec.max) return null;
  return `https://haydockcommentary.com/${spec.slug}-${chapter}`;
}
