/**
 * Confirmed lapide.org chapter files. Omit a book rather than risk a 404.
 * Job and Psalms were never published in Lapide’s commentary.
 */
export const LAPIDE_SLUG: Record<string, { file: string; max: number }> = {
  Genesis: { file: "01_genesis", max: 50 },
  Exodus: { file: "02_exodus", max: 40 },
  Leviticus: { file: "03_leviticus", max: 27 },
  Numbers: { file: "04_numeri", max: 36 },
  Deuteronomy: { file: "05_deuteronomium", max: 34 },
  Joshua: { file: "06_josue", max: 24 },
  Judges: { file: "07_judicum", max: 21 },
  Ruth: { file: "08_ruth", max: 4 },
  "1 Samuel": { file: "09_i_regum", max: 31 },
  "2 Samuel": { file: "10_ii_regum", max: 24 },
  "1 Kings": { file: "11_iii_regum", max: 22 },
  "2 Kings": { file: "12_iv_regum", max: 25 },
  "1 Chronicles": { file: "13_i_paralipomenon", max: 29 },
  "2 Chronicles": { file: "14_ii_paralipomenon", max: 36 },
  Ezra: { file: "15_i_esdrae", max: 10 },
  Nehemiah: { file: "16_ii_esdrae", max: 13 },
  Tobit: { file: "17_tobiae", max: 14 },
  Judith: { file: "18_judith", max: 16 },
  Esther: { file: "19_esther", max: 16 },
  "1 Maccabees": { file: "20_i_machabaeorum", max: 16 },
  "2 Maccabees": { file: "21_ii_machabaeorum", max: 15 },
  Proverbs: { file: "22_proverbia", max: 31 },
  Ecclesiastes: { file: "23_ecclesiastes", max: 12 },
  "Song of Songs": { file: "24_canticum", max: 8 },
  Wisdom: { file: "25_sapientia", max: 19 },
  Sirach: { file: "26_ecclesiasticus", max: 51 },
  Isaiah: { file: "27_isaias", max: 66 },
  Jeremiah: { file: "28_jeremias", max: 52 },
  Lamentations: { file: "29_threni", max: 5 },
  Baruch: { file: "30_baruch", max: 6 },
  Ezekiel: { file: "31_ezechiel", max: 48 },
  Daniel: { file: "32_daniel", max: 14 },
  Hosea: { file: "34_osee", max: 14 },
  Joel: { file: "35_joel", max: 3 },
  Amos: { file: "36_amos", max: 9 },
  Obadiah: { file: "37_abdias", max: 1 },
  Jonah: { file: "38_jonas", max: 4 },
  Micah: { file: "39_micheas", max: 7 },
  Nahum: { file: "40_nahum", max: 3 },
  Habakkuk: { file: "41_habacuc", max: 3 },
  Zephaniah: { file: "42_sophonias", max: 3 },
  Haggai: { file: "43_aggaeus", max: 2 },
  Zechariah: { file: "44_zacharias", max: 14 },
  Malachi: { file: "45_malachias", max: 4 },
  Matthew: { file: "46_matthaeus", max: 28 },
  Mark: { file: "50_marcus", max: 16 },
  Luke: { file: "52_lucas", max: 24 },
  John: { file: "54_joannes", max: 21 },
  "Acts of the Apostles": { file: "57_acts", max: 28 },
  Romans: { file: "59_romanos", max: 16 },
  "1 Corinthians": { file: "60_i_corinthios", max: 16 },
  "2 Corinthians": { file: "61_ii_corinthios", max: 13 },
  Galatians: { file: "62_galatas", max: 6 },
  Ephesians: { file: "63_ephesios", max: 6 },
  Philippians: { file: "64_philippenses", max: 4 },
  Colossians: { file: "65_colossenses", max: 4 },
  "1 Thessalonians": { file: "66_i_thessalonicenses", max: 5 },
  "2 Thessalonians": { file: "67_ii_thessalonicenses", max: 3 },
  "1 Timothy": { file: "68_i_timotheum", max: 6 },
  "2 Timothy": { file: "69_ii_timotheum", max: 4 },
  Titus: { file: "70_titum", max: 3 },
  Philemon: { file: "71_philemonem", max: 1 },
  Hebrews: { file: "72_hebraeos", max: 13 },
  James: { file: "74_iacobi", max: 5 },
  "1 Peter": { file: "75_i_petri", max: 5 },
  "2 Peter": { file: "76_ii_petri", max: 3 },
  "1 John": { file: "77_i_joannis", max: 5 },
  "2 John": { file: "78_ii_joannis", max: 1 },
  "3 John": { file: "79_iii_joannis", max: 1 },
  Jude: { file: "80_judae", max: 1 },
  Revelation: { file: "81_apocalypsis", max: 22 },
};

export function lapideUrl(book: string, chapter: number): string | null {
  const spec = LAPIDE_SLUG[book];
  if (!spec || chapter < 1 || chapter > spec.max) return null;
  return `https://lapide.org/${spec.file}_${String(chapter).padStart(2, "0")}.html`;
}
